### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by juan-vfx** [tarantulaVFX/Kitsu4Nuke#1]
I have this error when starting
Traceback (most recent call last):
  File ".nuke/Kitsu4Nuke/menu.py", line 12, in <module>
    import Kitsu4Nuke
  File ".nuke/Kitsu4Nuke\Kitsu4Nuke.py", line 9, in <module>
    from KitsuLogin import KitsuLogin
  File ".nuke/Kitsu4Nuke\KitsuLogin.py", line 9, in <module>
    from KitsuUtil import KitsuSession, setConfig, getConfig, empty_conf
ImportError: cannot import name KitsuSession

**Comment by lukas-remis** [comment]
I have the same problem
